alias vi="vim"
alias cl="clear"
alias ll="ls -la"
alias jedi="ssh info"
alias gc="git commit -m"
alias gp="git push"
alias grep="grep --colour=auto"
alias testa_tudo="rspec spec/business/ && rspec spec/decorators/ && rspec spec/lib/ && rspec spec/enumerations/ && rspec spec/models/"
