alias vi="vim"
alias cl="clear"
alias ll="ls -la"
alias tmux="TERM=screen-256color-bce tmux"
alias labs="ssh infoslack -t tmux a"
alias vpn="/opt/openvpn/start"
alias bx="bundle exec"
alias grep="grep --colour=auto"
alias monitor_2="xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1"
alias privchrome="google-chrome --user-data-dir --proxy-server=\"127.0.0.1:8118\""
alias cam='mplayer -tv driver=v4l2:device=/dev/video0 tv://'
