alias vi="vim"
alias cl="clear"
alias ll="ls -la"
alias tmux="TERM=screen-256color-bce tmux"
alias labs="ssh infoslack -t tmux a"
alias bx="bundle exec"
alias grep="grep --colour=auto"
alias cpu_default="sh ~/.my_bash/scripts/cpu_default.sh"
alias cpu_conservative="sh ~/.my_bash/scripts/cpu_conservative.sh"
alias cpu_custom_ondemand="sh ~/.my_bash/scripts/cpu_custom_ondemand.sh"
alias cpu_custom_conservative="sh ~/.my_bash/scripts/cpu_custom_conservative.sh"
alias cpu_2_off="echo 0 > /sys/devices/system/cpu/cpu2/online"
alias cpu_3_off="echo 0 > /sys/devices/system/cpu/cpu3/online"
alias cpu_2_on="echo 1 > /sys/devices/system/cpu/cpu2/online"
alias cpu_3_on="echo 1 > /sys/devices/system/cpu/cpu3/online"
alias monitor_2="xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1"
alias privchrome="google-chrome --user-data-dir --proxy-server=\"socks://127.0.0.1:9050\""
