source ~/.bash/export.sh
source ~/.bash/alias.sh
source ~/.bash/dockerfunc.sh
source ~/.bash/prompt.sh
source /etc/profile.d/git-completion.bash

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/google-cloud-sdk/path.bash.inc' ]; then source '/opt/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/google-cloud-sdk/completion.bash.inc' ]; then source '/opt/google-cloud-sdk/completion.bash.inc'; fi
